export default [
    './assets/portfolio/Cookiespam.png',
    './assets/portfolio/Date_Mermaid.png',
    './assets/portfolio/FTB13_PlumDepths.png',
    './assets/portfolio/FTB11_One_melon.png',
    './assets/portfolio/FTB12_Passionfruit.png',

    './assets/portfolio/FTB14_Meloncholy.png',
    './assets/portfolio/FTB15_Meloncholy.png',
    './assets/portfolio/FTB16_PeachPearDAD.png',
    './assets/portfolio/FTB17_RaisinsWhy.png',
    './assets/portfolio/FTB18_Guavity2.png',
    './assets/portfolio/FTB19_Mandarin.png',
    './assets/portfolio/FTB1_PeachMaad.png',
    './assets/portfolio/FTB20_PunchLime.png',
    './assets/portfolio/FTB21_BananaTape.png',
    './assets/portfolio/FTB22_Disappear.png',
    './assets/portfolio/FTB21_Compassion.png',

    './assets/portfolio/FTB23_Berried copy.png',
    './assets/portfolio/FTB23_FigDiff copy.png',
    './assets/portfolio/FTB25_bigapple copy.png',
    './assets/portfolio/FTB26_BananaTape.png',
    './assets/portfolio/FTB27_maddmadd copy.png',
    './assets/portfolio/FTB28_olive copy.png',
    './assets/portfolio/FTB29_AppleEye copy.png',
    './assets/portfolio/FTB30_CocoPeach.png',
    './assets/portfolio/FTB31_MelonMusk.png',
    './assets/portfolio/FTB3_Speachless.png',
    './assets/portfolio/FTB4_RaisinsWhy.png',
    './assets/portfolio/FTB5_SaveDate.png',
    './assets/portfolio/FTB6_Zestdoit.png',
    './assets/portfolio/FTB7_ForbiddenFruit copy.png',
    './assets/portfolio/FTB8_Berries.png',
    './assets/portfolio/FTB9_cherrycherry copy.png',
    './assets/portfolio/No sounds Space.png',
    './assets/portfolio/Pearfect.png',
    './assets/portfolio/dig more.png',
    './assets/portfolio/escpam.png',
    './assets/portfolio/lovethesong.png',

    './assets/portfolio/humanz die copy.png',
    './assets/portfolio/loadingpalette.png',
    './assets/portfolio/locationpm.png',
    './assets/portfolio/hatepm.png',
    './assets/portfolio/nofeelingpam.png',
    './assets/portfolio/persimmon.png',
    './assets/portfolio/pinklake.png',
    './assets/portfolio/underwater robot.png',
    './assets/portfolio/pinkvoid.png'

]